on: [push, pull_request]

name: Continuous integration

jobs:
  check:
    name: Compile and Test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        toolchain:
          - nightly
          - stable
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install ${{ matrix.toolchain }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt
      # TODO: enable once the differences are resolved
      #- name: cargo fmt --check
      #  run: cargo fmt --check
      - run: cargo build
      - run: cargo test
      - run: cargo test --doc
